Добавить классы Film, User
PAZderev/java-filmorate pull request #5
Opened 2024-06-08 07:30 UTC by PAZderev

Реализовать контроллеры для созданных классов

2024-06-08 09:46 UTC, db-exp requested changes

2024-06-08 09:46 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Long id;
можно NotNull добавить

2024-06-08 09:46 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void validateFilm(Film film) {
just for your interest https://www.baeldung.com/spring-mvc-custom-validator можно делать кастомные валидаторы

2024-06-08 11:43 UTC, PAZderev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Long id;
Нельзя, т.к. id генерируется при вызове метода addFilm. В аргументы приходит json без поля id. При такой логике NotNull нарушает логику работы

2024-06-08 12:56 UTC, PAZderev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void validateFilm(Film film) {
Сделал, спасибо за ссылку )

2024-06-08 12:57 UTC, PAZderev commented
Прошу обратить внимание на класс GlobalExceptionHandler, насколько это норм решение, чтобы логировать ошибки валидации jakarta

2024-06-09 18:20 UTC, db-exp approved these changes

2024-06-09 18:20 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Long id;
хм, согласен

2024-06-09 18:20 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/utils/GlobalExceptionHandler.java
> +@RestControllerAdvice
вполне ок)

2024-06-23 15:59 UTC, merged