Разделить контроллеры на слои Storage, Service
PAZderev/java-filmorate pull request #6
Opened 2024-06-26 09:12 UTC by PAZderev

Добавить логику по добавлению друзей, лайков к фильмам

2024-06-26 16:10 UTC, db-exp requested changes

2024-06-26 16:10 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film getFilmById(@PathVariable long id) {
можно Positive/NotNull

2024-06-26 16:10 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public boolean deleteFilm(@PathVariable long id) {
как и выше - Positive/NotNull

2024-06-26 16:10 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @PutMapping("/{id}/like/{userId}")
тоже самое и ниже

2024-06-26 16:10 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public boolean deleteUser(@PathVariable long userId) {
как в фильмах можно

2024-06-26 16:10 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/utils/GlobalExceptionHandler.java
> +    @ExceptionHandler({FriendOperationException.class, LikeOperationException.class})
на самом деле можно так не дробить исключения и ограничиться общим

2024-06-27 10:06 UTC, PAZderev commented
Спасибо за ревью!

2024-06-29 08:36 UTC, PAZderev commented
Возник вопрос, в коммерческой разработке логирование внутри методов в начале и в конце, сообщающие о начале и конце работы метода, как у меня (по типу добавление друга; друг добавлен) чаще выносят в отдельные классы - прокси или так и делают, что пишут логи внутри методов с бизнес-логикой? 
Если первый вариант, то можно какой-нибудь совет, где про это почитать, чтобы сделать самому)

2024-06-29 19:29 UTC, db-exp approved these changes

2024-07-02 14:02 UTC, merged